apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet

metadata:
  name: platform-applications

spec:

  generators:

    - git:

        repoURL: https://github.com/kosebinu/platform-engineering-bootcamp.git
        revision: main
        directories:
          - path: gitops/applications/*

  template:

    metadata:
      name: "{{path.basename}}"

    spec:
      project: default

      source:
        repoURL: https://github.com/kosebinu/platform-engineering-bootcamp.git
        targetRevision: main
        path: helm/charts/application-template

        helm:
          valueFiles:
            - "../../gitops/applications/{{path.basename}}/values-dev.yaml"

      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true