# -----------------------------------------------------------------------------
# Application Information
# -----------------------------------------------------------------------------

application:
  name: ""
  team: ""
  environment: dev

# -----------------------------------------------------------------------------
# Container Image
# -----------------------------------------------------------------------------

image:
  repository: ""
  tag: "latest"
  pullPolicy: IfNotPresent

# -----------------------------------------------------------------------------
# Deployment
# -----------------------------------------------------------------------------

replicaCount: 2