# -----------------------------------------------------------------------------
# Application Information
# -----------------------------------------------------------------------------

application:
  name: ""
  team: ""
  environment: dev

# -----------------------------------------------------------------------------
# Container Image
# -----------------------------------------------------------------------------

image:
  repository: ""
  tag: "latest"
  pullPolicy: IfNotPresent

# -----------------------------------------------------------------------------
# Deployment
# -----------------------------------------------------------------------------

replicaCount: 2

# -----------------------------------------------------------------------------
# Service
# -----------------------------------------------------------------------------

service:
  port: 8080

# -----------------------------------------------------------------------------
# Application Configuration
# -----------------------------------------------------------------------------

config: {}

# -----------------------------------------------------------------------------
# Application Secrets
# -----------------------------------------------------------------------------

secrets: {}