apiVersion: v1
kind: Secret

metadata:
  name: {{ .Values.application.name }}-secret

type: Opaque

stringData:
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
{{- end }}