apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.application.name }}

  labels:
    app.kubernetes.io/name: {{ .Values.application.name }}
    app.kubernetes.io/managed-by: Helm
    company.io/team: {{ .Values.application.team }}
    company.io/environment: {{ .Values.application.environment }}

spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: {{ .Values.application.name }}

  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP